package com.shop.core.constant;

public enum Reason {

	NEW_ASSIGNMENT,
	NEW_HIRE,
	MARITAL_STATUS,
	PERSONNEL_CONTACT_CHANGE,
	TRANSFER,
	TRANSFER_WITHIN_GROUP,
	RELIGION,
	HOME_BASE,
	END_SETUP,
	EMPLOYMENT_CATEGORY,
	NEW_VERSION,
	CHANGE_INTERNAL_MARRIED,
	TERMINATE_INTERNAL_MARRIED_WITH,
	NEW_SETUP,
	TRANSFER_BY_COMPANY;
}
