package com.shop.core.domain;

import java.io.Serializable;
import java.util.Date;

public class Kelurahan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KELURAHAN_TEST.KEL_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String kelurahanCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KELURAHAN_TEST.KELURAHAN
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String kelurahan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KELURAHAN_TEST.KEC_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String kecCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KELURAHAN_TEST.CREATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KELURAHAN_TEST.CREATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KELURAHAN_TEST.UPDATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KELURAHAN_TEST.UPDATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FS_MST_KELURAHAN_TEST
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KELURAHAN_TEST.KEL_CODE
     *
     * @return the value of FS_MST_KELURAHAN_TEST.KEL_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getKelurahanCode() {
        return kelurahanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KELURAHAN_TEST.KEL_CODE
     *
     * @param kelurahanCode the value for FS_MST_KELURAHAN_TEST.KEL_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setKelurahanCode(String kelurahanCode) {
        this.kelurahanCode = kelurahanCode == null ? null : kelurahanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KELURAHAN_TEST.KELURAHAN
     *
     * @return the value of FS_MST_KELURAHAN_TEST.KELURAHAN
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getKelurahan() {
        return kelurahan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KELURAHAN_TEST.KELURAHAN
     *
     * @param kelurahan the value for FS_MST_KELURAHAN_TEST.KELURAHAN
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setKelurahan(String kelurahan) {
        this.kelurahan = kelurahan == null ? null : kelurahan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KELURAHAN_TEST.KEC_CODE
     *
     * @return the value of FS_MST_KELURAHAN_TEST.KEC_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getKecCode() {
        return kecCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KELURAHAN_TEST.KEC_CODE
     *
     * @param kecCode the value for FS_MST_KELURAHAN_TEST.KEC_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setKecCode(String kecCode) {
        this.kecCode = kecCode == null ? null : kecCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KELURAHAN_TEST.CREATE_BY
     *
     * @return the value of FS_MST_KELURAHAN_TEST.CREATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KELURAHAN_TEST.CREATE_BY
     *
     * @param createBy the value for FS_MST_KELURAHAN_TEST.CREATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KELURAHAN_TEST.CREATE_DATE
     *
     * @return the value of FS_MST_KELURAHAN_TEST.CREATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KELURAHAN_TEST.CREATE_DATE
     *
     * @param createDate the value for FS_MST_KELURAHAN_TEST.CREATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KELURAHAN_TEST.UPDATE_BY
     *
     * @return the value of FS_MST_KELURAHAN_TEST.UPDATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KELURAHAN_TEST.UPDATE_BY
     *
     * @param updateBy the value for FS_MST_KELURAHAN_TEST.UPDATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KELURAHAN_TEST.UPDATE_DATE
     *
     * @return the value of FS_MST_KELURAHAN_TEST.UPDATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KELURAHAN_TEST.UPDATE_DATE
     *
     * @param updateDate the value for FS_MST_KELURAHAN_TEST.UPDATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}