package com.fif.hcms.core.domain;

import java.io.Serializable;
import java.util.Date;

public class Kecamatan implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KECAMATAN_TEST.KEC_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String kecamatanCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KECAMATAN_TEST.KECAMATAN
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String kecamatan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KECAMATAN_TEST.CITY_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KECAMATAN_TEST.CREATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KECAMATAN_TEST.CREATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KECAMATAN_TEST.UPDATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FS_MST_KECAMATAN_TEST.UPDATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FS_MST_KECAMATAN_TEST
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KECAMATAN_TEST.KEC_CODE
     *
     * @return the value of FS_MST_KECAMATAN_TEST.KEC_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getKecamatanCode() {
        return kecamatanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KECAMATAN_TEST.KEC_CODE
     *
     * @param kecamatanCode the value for FS_MST_KECAMATAN_TEST.KEC_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setKecamatanCode(String kecamatanCode) {
        this.kecamatanCode = kecamatanCode == null ? null : kecamatanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KECAMATAN_TEST.KECAMATAN
     *
     * @return the value of FS_MST_KECAMATAN_TEST.KECAMATAN
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getKecamatan() {
        return kecamatan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KECAMATAN_TEST.KECAMATAN
     *
     * @param kecamatan the value for FS_MST_KECAMATAN_TEST.KECAMATAN
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setKecamatan(String kecamatan) {
        this.kecamatan = kecamatan == null ? null : kecamatan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KECAMATAN_TEST.CITY_CODE
     *
     * @return the value of FS_MST_KECAMATAN_TEST.CITY_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KECAMATAN_TEST.CITY_CODE
     *
     * @param cityCode the value for FS_MST_KECAMATAN_TEST.CITY_CODE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KECAMATAN_TEST.CREATE_BY
     *
     * @return the value of FS_MST_KECAMATAN_TEST.CREATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KECAMATAN_TEST.CREATE_BY
     *
     * @param createBy the value for FS_MST_KECAMATAN_TEST.CREATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KECAMATAN_TEST.CREATE_DATE
     *
     * @return the value of FS_MST_KECAMATAN_TEST.CREATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KECAMATAN_TEST.CREATE_DATE
     *
     * @param createDate the value for FS_MST_KECAMATAN_TEST.CREATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KECAMATAN_TEST.UPDATE_BY
     *
     * @return the value of FS_MST_KECAMATAN_TEST.UPDATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KECAMATAN_TEST.UPDATE_BY
     *
     * @param updateBy the value for FS_MST_KECAMATAN_TEST.UPDATE_BY
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FS_MST_KECAMATAN_TEST.UPDATE_DATE
     *
     * @return the value of FS_MST_KECAMATAN_TEST.UPDATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FS_MST_KECAMATAN_TEST.UPDATE_DATE
     *
     * @param updateDate the value for FS_MST_KECAMATAN_TEST.UPDATE_DATE
     *
     * @mbggenerated Thu Feb 28 18:40:22 ICT 2013
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}